FROM python:3.11-slim-bookworm

ENV DEBIAN_FRONTEND=noninteractive
WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY uploader.py .

ENV PYTHONUNBUFFERED=1
CMD ["python", "uploader.py"]
